### ISSUE TITLE
panic:  field of "url" is required 

### ISSUE THREAD

**Issue by apllebreh** [metafates/mangal-scrapers#28]
An error occurs when trying to pull pages from mangasee that don't have the -page- in the url
For comparison
read-online/random-series-chapter-1-page-1.html 
loads perfectly

read-online/random-other-series-chapter-1.html 
breaks the program with the following as the output

panic:  field of "url" is required                                                                                                                                                                                    
stack traceback:
	[G]: ?

goroutine 191 [running]:
github.com/yuin/gopher-lua.panicWithTraceback(0xc0003dec40?)
	github.com/yuin/gopher-lua@v1.0.0/state.go:601 +0xa5
github.com/yuin/gopher-lua.(*LState).raiseError(0xc000432160, 0x1, {0xc0003dec20?, 0x1a?}, {0x0?, 0x0?, 0x0?})
	github.com/yuin/gopher-lua@v1.0.0/state.go:696 +0x25d
github.com/yuin/gopher-lua.(*LState).RaiseError(...)
	github.com/yuin/gopher-lua@v1.0.0/state.go:1671
github.com/metafates/mangal/provider/custom.(*luaSource).PagesOf.func1({0x156dc20, 0xc0005da238}, {0x156cfe0?, 0xc0005ac3c0?})
	github.com/metafates/mangal/provider/custom/pages.go:31 +0x1f5
github.com/yuin/gopher-lua.(*LTable).ForEach(0xc0005ac120, 0xc000765c58)
	github.com/yuin/gopher-lua@v1.0.0/table.go:330 +0x2fa
github.com/metafates/mangal/provider/custom.(*luaSource).PagesOf(0xc0000b9e60, 0xc00053b680)
	github.com/metafates/mangal/provider/custom/pages.go:19 +0x135
github.com/metafates/mangal/downloader.Download(0xc00053b680, 0xc00051f660)
	github.com/metafates/mangal/downloader/download.go:43 +0x359
github.com/metafates/mangal/tui.(*statefulBubble).downloadChapter.func1()
	github.com/metafates/mangal/tui/handlers.go:250 +0x98
github.com/charmbracelet/bubbletea.(*Program).handleCommands.func1.1()
	github.com/charmbracelet/bubbletea@v0.23.1/tea.go:247 +0x38
created by github.com/charmbracelet/bubbletea.(*Program).handleCommands.func1
	github.com/charmbracelet/bubbletea@v0.23.1/tea.go:246 +0x14d

**Comment by apllebreh** [comment]
i'm sorry, I just noticed this was already mentioned in another issue.
