### ISSUE TITLE
ComicK exceeds http timeout

### ISSUE THREAD

**Issue by metafates** [metafates/mangal-scrapers#4]
<img width="1010" alt="Screenshot 2022-10-21 at 12 15 31" src="https://user-images.githubusercontent.com/62389790/197160420-e33ead88-6ca6-42cc-a3e8-07f0b3f3b6ab.png">

**Comment by balajsra** [comment]
Can confirm that it is not working. I'm getting the following error when searching for anything:

```bash
panic:  field of "name" is required
stack traceback:
	[G]: ?

goroutine 72 [running]:
github.com/yuin/gopher-lua.panicWithTraceback(0xc000816020?)
	github.com/yuin/gopher-lua@v0.0.0-20220504180219-658193537a64/state.go:601 +0xa5
github.com/yuin/gopher-lua.(*LState).raiseError(0xc0003308f0, 0x1, {0xc000816000?, 0x1b?}, {0x0?, 0x0?, 0x0?})
	github.com/yuin/gopher-lua@v0.0.0-20220504180219-658193537a64/state.go:696 +0x25d
github.com/yuin/gopher-lua.(*LState).RaiseError(...)
	github.com/yuin/gopher-lua@v0.0.0-20220504180219-658193537a64/state.go:1671
github.com/metafates/mangal/provider/custom.(*luaSource).Search.func1({0x14f7a80, 0xc000682d70}, {0x14f6e40?, 0xc0006bda40?})
	github.com/metafates/mangal/provider/custom/search.go:41 +0x275
github.com/yuin/gopher-lua.(*LTable).ForEach(0xc0006bd680, 0xc000431ea0)
	github.com/yuin/gopher-lua@v0.0.0-20220504180219-658193537a64/table.go:330 +0x2fa
github.com/metafates/mangal/provider/custom.(*luaSource).Search(0xc00024f470, {0xc000400040, 0xa})
	github.com/metafates/mangal/provider/custom/search.go:24 +0x148
github.com/metafates/mangal/tui.(*statefulBubble).searchManga.func1.1({0x14f6cc0, 0xc00024f470})
	github.com/metafates/mangal/tui/handlers.go:157 +0xb5
created by github.com/metafates/mangal/tui.(*statefulBubble).searchManga.func1
	github.com/metafates/mangal/tui/handlers.go:155 +0x405
```

Tried to debug using `mangal run ./ComicK.lua` as described in the [main repo's README](https://github.com/metafates/mangal#custom-scrapers), but nothing happens. Not sure how to proceed from here.

**Comment by metafates** [comment]
@balajsra I'll take a look later.

`mangal run ...` will run the given file so you can do anything inside it. E.g.

```lua
-- ComicK.lua
-- code above...

print("hello?")
```

```shell
$ mangal run ./ComicK.Lua
hello?
```

**Comment by metafates** [comment]
Okay, looks like the problem is that server is too slow and mangal gives http timeout after 10 seconds of not responding. I've changed timeout to 20s but looks like http Lua library has some bugs in it and timeout is not applying properly.

Currently, ComicK works like 4 times out of 5

**Comment by metafates** [comment]
I've fixed client timeout, everything should be fine now
