### ISSUE TITLE
When using Mangasee headless chromium-1033860 browser crashes on some entries.

### ISSUE THREAD

**Issue by jspaces** [metafates/mangal-scrapers#6]
When I try to download some chapters on certain manga entries on MangaSee headless chromium connector version 1033860; mangal crashes with the following error. I am using the latest git version of the scrapers and mangal itself. 
The following example entry crashes each and every time I tried.
My Isekai Life - I Gained a Second Character Class and Became the Strongest Sage in the World  
┃ https://mangasee123.com/manga/Tensei-Kenja-No-Isekai-Raifu                 
```
esc back • ctrl+c quit                                                                                                     
panic:  field of "url" is required                                                                                           
stack traceback:
	[G]: ?

goroutine 197 [running]:
github.com/yuin/gopher-lua.panicWithTraceback(0xc0005809c0?)
	<PATH>/mangal/vendor/github.com/yuin/gopher-lua/state.go:601 +0xa5
github.com/yuin/gopher-lua.(*LState).raiseError(0xc000398000, 0x1, {0xc0005809a0?, 0x1a?}, {0x0?, 0x0?, 0x0?})
	<PATH>/mangal/vendor/github.com/yuin/gopher-lua/state.go:696 +0x25d
github.com/yuin/gopher-lua.(*LState).RaiseError(...)
	<PATH>/mangal/vendor/github.com/yuin/gopher-lua/state.go:1671
github.com/metafates/mangal/provider/custom.(*luaSource).PagesOf.func1({0x15526a0, 0xc0003cd0b0}, {0x1551a60?, 0xc0001438c0?})
	<PATH>/mangal/provider/custom/pages.go:31 +0x1f5
github.com/yuin/gopher-lua.(*LTable).ForEach(0xc000143680, 0xc0005d9c60)
	<PATH>/mangal/vendor/github.com/yuin/gopher-lua/table.go:330 +0x2fa
github.com/metafates/mangal/provider/custom.(*luaSource).PagesOf(0xc000504900, 0xc00069e200)
	<PATH>/mangal/provider/custom/pages.go:19 +0x135
github.com/metafates/mangal/downloader.Download(0xc00069e200, 0xc00045af50)
	<PATH>/mangal-git/src/mangal/downloader/download.go:43 +0x359
github.com/metafates/mangal/tui.(*statefulBubble).downloadChapter.func1()
	<PATH>/mangal/tui/handlers.go:250 +0x98
github.com/charmbracelet/bubbletea.(*Program).StartReturningModel.func6.1()
	<PATH>/mangal/vendor/github.com/charmbracelet/bubbletea/tea.go:469 +0x33
created by github.com/charmbracelet/bubbletea.(*Program).StartReturningModel.func6
	<PATH>/mangal/vendor/github.com/charmbracelet/bubbletea/tea.go:467 +0x14d
```
 I also found several other entries/links. It seems that if the entry has many chapters, it fails with the "url is required" 
message. Though one with 117 chapters did successfully download. The above example only had 73 chapters to be downloaded. I did try to download several single chapters randomly and it result was the same.

**Comment by apllebreh** [comment]
For me it breaks when the -page- addon is missing in the url 

read-online/random-series-chapter-1-page-1.html
loads perfectly

read-online/random-other-series-chapter-1.html
breaks the program
